# Generated by Django 4.1 on 2022-09-01 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='image',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='lte_exists',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='price',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='slug',
        ),
    ]
